### ISSUE TITLE
Arisa also comments on tickets that have already been resolved before the last run

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#272] opened 2020-05-22 10:01 UTC
## The Bug
When a duplicate ticket is re-linked to link to another ticket, Arisa will leave a comment if that ticket hasn't been mentioned before. This happens even if Arisa does this. In my opinion, this is not desirable since it's likely that there was already another duplicate message before.

## Example Ticket
https://bugs.mojang.com/browse/MC-184703

## Expected behavior
Do not leave a duplicate comment on tickets that have been resolved before `lastRun - commentDelay`, or something along those lines.

**Comment by NeunEinser** [comment] 2020-05-22 12:10
Haha, that's a fun example. It's like the bot pretends to know better, as the bot also did the relinking in TransferLinks.

**Comment by NeunEinser** [comment] 2020-05-22 12:17
Tbh, it might be better to see if no link that has been mentioned in a comment was ever linked as a duplicates link in the history of the ticket.

This would imply no comment is added, if one ticket has been mentioned, but tbh, I don't think we need to add a comment if someone said "duplicates MC-108" and we end up resolving as dupe of MC-108 and MC-11193

**Comment by violine1101** [comment] 2020-05-22 12:28
Arisa also leaves the duplicate ticket on tickets it shouldn't. In this case, it comments on tickets that have been resolved ages ago, but have been updated recently. I don't think it should do that.

See: https://bugs.mojang.com/browse/MC-99969

**Closed** 2020-05-22 16:00 UTC
Labels: bug
