### ISSUE TITLE
Automatically add affected versions based on comments

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#400] opened 2020-07-31 16:53 UTC
## The Problem
Updating affected versions based on comments by users is probably one of the biggest tasks performed by helpers and moderators. Usually we rely on the version the user mentioned and do not verify ourselves that the issue still occurs (do projects other than MC handle this differently?).
However, this task is pretty repetitive and can be quite tedious especially when working based on e-mail notifications because you often have to open the report and check whether the affected version has already been added by another helper / moderator or the reporter.

With the changes introduced by the recent Jira updates, e-mail notifications are now grouped so an update to the affected versions would be sent together with the comment if they happen soon after each other.
It would there be even more useful to have Arisa automatically add affected versions.
It would likely have a similar effect on the activity feed as well when the comment and the update of the affected versions are close to each other.

## Possible Implementation
The module should detect comment creation and possibly edits as well (?) (sometimes users update their comment when a new version is released) and determine if the comment looks like it confirms a bug.

### Comment matching
There are some common phrases used:
- >Can confirm for 1.13-pre3
- >Confirmed for 20w18a.
- >Still in 13w01b.
- >Affects 1.16 pre release 2
- >Still happens in 20w27a
- >Confirmed in 1.16-pre5.
- >Present in 1.13.1
- >Issue still exists in 1.14.4
- >In 1.16.1

  Note: Personally I would not include this since it could also indicate an incomplete sentence where the user added the comment by accident, e.g. "In 1.16.1 I cannot reproduce it anymore".

To prevent false positives the module should match the complete comment text (and not only check if the phrase is contained).

Additionally it would be useful to:
- Detect two versions (usually latest snapshot and release) joined with <code>&nbsp;and&nbsp;</code> or with either of `,`, `+`, `&`, `/` (optionally surrounded with spaces) e.g.:
  > Confirmed for 1.16.1 and 1.16.2-pre1
- Consider an optional "version", "release", "snapshot" or "minecraft" in front of a version name, e.g.
  > Confirmed for version 1.16.1

  Possibly even in combination with a second version, e.g.:
  > Confirmed for version 1.16.1 and _[version]_ 1.16.2-pre1
- Ignore trailing periods
- Match case insensitively (using `Locale.ENGLISH`)
- Consider version display names and version IDs (if possible), e.g. both "1.16.2-pre1" and "1.16.2 Pre release 1" should work
- Consider alternative version name spelling
  - For pre-releases: "1.16.2 prerelease 1", "1.16.2 pre release 1", "1.16.2-pre1", "1.16.2pre1", "1.16.2pre-1", "1.16.2 pre 1", "1.16.2pr1"
  - For release candidates: _?_

### Updating logic
The logic for updating the affected versions could therefore look like this:
When a comment is added or an existing comment is edited:
1. Make sure that the report is unresolved or resolved as "Awaiting Response"
2. Make sure the comment has no security level
3. Optional: Skip execution if all available non-archived versions are already set as affected
This could increase performance if pattern matching of comments is expensive.
4. Check if the comment matches one of the patterns described above
5. For each matched version:
    1. Skip archived versions
    2. Skip future versions
    3. Skip versions already marked as affected
    4. Skip a version if it will already be added (e.g. if user comments for some reason same version twice)
    5. Add the affected version

## Considerations
- Make sure the module interacts correctly with other modules, e.g. does not run when another module would resolve a report
- Protect against abuse?
A malicious user might be able to write a script adding comments triggering this behavior on hundres of reports. Would it be possible to determine how many of such "confirming comments" a user has written in the past _X_ minutes and if it exceeds a certain threshold not perform any action? Though maybe this case is rather unlikely.
Possibly also add a whitelist for "trusted users" in case there are users who reach the threshold too often. Though such whitelist could be added at a later point if it turns out to be required.
- A user might type "can" instead of "can't" by accident.
Though this is likely rather rare (but has happened if I recall correctly).
- A user might make a typo in the version name.
Since the module should only consider non-archived versions and does not perform any action otherwise this is likely not an issue.
- Maybe it would be good if Arisa logged a message when this module adds versions. Since there are other modules which transfer affected versions it can otherwise become confusing / non-obvious why Arisa added an affected version, especially when there is a large backlog.
- This module might make users, who previously used the Discord server for affected version requests, add comments instead, increasing the "spam" caused by such comments.

## Optional features
- Possibly if the comment is by someone other than the reporter (and actually matched valid non-archived versions) also set the Confirmation Status to "Community Consensus" for unconfirmed reports?
- If the reporter wrote the comment, Arisa should additionally to adding the version(s) comment something like this:
  > @[~_user_], since you are the reporter you can update affected versions without having to comment. You can do so by clicking next to the **Affects Version/s:** text and typing the respective version.

----

This is only an enhancement idea, even if the module only considers a fraction of the aspects mentioned here, it would likely be useful enough.
Any feedback is appreciated.

**Comment by dericksonmark** [comment] 2020-08-01 03:23
Hello! This sounds like a really good idea. Currently, I would assume that it's a really tedious task to add affected versions, especially when there's a period of time where no helpers are available to check requests. I remember that LateLag once spent 3 hours sorting through requests that built up over the course of about 30 hours. The fact that this could be automated is quite impressive. A bit of feedback I have after reading through the ticket:

- Allow commas, ampersands, plus signs, and forward slashes in addition to 'and' in conjunctions of version names, ex.: In 1.16.1/20w30a.
- In conjunctions of version names, a space between the conjunction and the name should not be necessary but accepted whether or not it is present, ex.: In 1.16.1+20w30a; In 1.16.1 +20w30a; In 1.16.1 + 20w30a could all be accepted.
- Allow for 'snapshot', 'release', and 'minecraft' to be added before the version names as well as 'version'.
- Variations of version names could all be accepted, for example "1.16.2 prerelease 1", "1.16.2 pre release 1", "1.16.2-pre1", "1.16.2pre1", "1.16.2pre-1", "1.16.2 pre 1", "1.16.2pr1" could all be accepted and be recognized as 1.16.2-pre1.
- Ignore any unreleased versions; in "confirmed in 20w30a and Future Version: 1.17+", only 20w30a should be accepted. 
- I like the idea you had for preventing against malicious users. I think that a user should only have requests accepted if they're at least 15 seconds apart, and they haven't made more than 50 requests in an hour. This will help prevent malicious users, but there's no way that I can think of to completely prevent it.
- I also really like the idea of adding community consensus to the ticket; especially for older tickets and for users who don't know about the Discord and can't make a request for community consensus on a ticket, it would be really beneficial for the ticket to be noticed.
- Awaiting Response resolutions could be accepted; for example, if a ticket is resolved as AR with the comment "Can anyone reproduce in the latest version?" and someone says "I can confirm in 1.16.1", then 1.16.1 should be added to the affected versions even though the ticket was marked as Awaiting Response.
- Greetings in the beginning could be ignored, for example: "Hi there! Confirmed for 20w30a." But you don't have to add that part. But it would be a good idea. :)

Overall, I think it's a pretty interesting concept, but it will likely take lots of development to perfect. There is so much variation in comments created by real people, that a bot reading through them might have a hard time sorting out the valid affects version comments from the "I can't confirm" comments.

:D

**Comment by Marcono1234** [comment] 2020-08-01 12:02
Thanks for you feedback! These are all good points, I have updated the description of this issue accordingly.

> Ignore any unreleased versions; in "confirmed in 20w30a and Future Version: 1.17+", only 20w30a should be accepted.

That is a really good point which I missed. Future versions are not archived so this could have caused some issues.

----

>"1.16.2pr1", "pre1", "prerelease 1" could all be accepted and be recognized as 1.16.2-pre1.

I have included "1.16.2pr1" in the description even though I don't think that it is very common.
The others should in my opinion not be matched since they are too vague. After all this module should not detect every case, but at least the most common ones.

----

> I like the idea you had for preventing against malicious users. _[...]_ Volunteers should not be affected by this limit

This is likely not an issue because volunteers (helpers and moderators) can add affected versions directly without having to comment.

----

> Greetings in the beginning could be ignored

This might make it too complex and introduce false positives. As pointed out above the module should not detect every case. Especially users who have worked a little bit with the bug tracker and who are the ones writing most of these comments tend to stick to the simple phrases outlined above.

**Comment by NeunEinser** [comment] 2020-08-01 12:43
I don't like the idea terribly much, as it's imo not that much effort, compared to other requests (basically everything else requires some checking) and we have more people that can resolve those requests, as helpers can do it as well and not only moderators.
If we go this far, we might as well give direct access for everyone to modify affected versions (if that's possible with Jira's permission system at least) and add bot functionality for bulk-removing versions a certain user added.

This is also definitely something that needs Mojang approval.

A different idea could be to ask people who make requests on Discord to provide a comma-separated list of issues they can confirm for a certain version instead as one request. We can just put those in a search query then (`key in (MC-1, MC-2, ...)` and do a bulk change to add versions and then do a search for `key in (...) AND "Confirmation Status" in (Unconfirmed, Plausible)` to assess confirmation status for those manually.

**Comment by dericksonmark** [comment] 2020-08-01 23:20
There are also some Mojira users who do a lot of helpful things on the tracker but don't actually know about the Discord, and because of this, they are unable to send requests.

An alternate implementation of this module could be using a set time period between the comment and the update, something like 12 hours, and if a moderator doesn't update the affected versions in that time period, Arisa could do it automatically. This is especially useful for older tickets that don't get a lot of attention.

I'll assume that not every volunteer has the time to check through every unconfirmed/unresolved ticket for a comment confirming the issue for the latest version, so by automatically updating the report when a comment like this is added, it gives the ticket a bit more priority and increases the chances of the previously (possibly) unnoticed issue to be noticed by developers.

**Comment by urielsalis** [comment] 2020-09-27 12:33
Closing after internal discussion

**Closed by urielsalis** 2020-09-27 12:33 UTC
Labels: discussion needed, enhancement, module
