### ISSUE TITLE
Arisa fails to transition WEB issues without component

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#714] opened 2021-07-11 11:09 UTC
## The Bug
Arisa fails to transition WEB issues without component
## Example Ticket
https://bugs.mojang.com/browse/WEB-1886
## Expected behavior
It should transition correctly

**Comment by Greymagic27** [comment] 2021-07-15 15:19
Duplicate of #661

**Closed by Greymagic27** 2021-07-15 15:19 UTC
Labels: bug
