### ISSUE TITLE
Restrict Arisa responses to commands to "staff" instead of "helper"

### ISSUE THREAD

**Issue by MikeUnverferth** [mojira/arisa-kt#502] opened 2020-12-11 13:24 UTC
## The Problem
Currently responses are restricted to "helper". However, the helpers correctly cannot see the actual commands since they are staff-restricted. This is likely to be confusing to helpers.

## Possible Solution
Restrict responses to staff group instead of helper.

**Comment by chandler05** [comment] 2020-12-11 14:51
Duplicate of #404

**Closed** 2020-12-11 14:52 UTC
Labels: duplicate, enhancement

**Comment by MikeUnverferth** [comment] 2020-12-11 14:54
I searched for a duplicate! Really I did. :(
