### ISSUE TITLE
Language module responded twice

### ISSUE THREAD

**Issue by IonicEcko** [mojira/arisa-kt#208] opened 2020-05-06 01:02 UTC
## The Bug
The language module responded twice on this ticket. May not matter but I've not seen it before.

## Example Ticket
https://bugs.mojang.com/browse/MCPE-75814

**Comment by violine1101** [comment] 2020-05-06 07:04
Reappearance of #197?

**Comment by NeunEinser** [comment] 2020-05-06 08:47
No, this is definitely not #197.
This is actually the module executing twice in the same instance of Arisa, in 2 successive runs. If Arisa was running twice, this would be very obvious from the logs and this seems to be the only instance from doing stuff twice.

The relevant log:
```
00:13:22.363 | main | INFO | Arisa | 104 | [RESPONSE] [MCPE-75815] [FutureVersion] Successful
00:13:25.247 | main | INFO | Arisa | 104 | [RESPONSE] [MCPE-75814] [Language] Successful
00:13:25.248 | main | INFO | Arisa | 104 | [RESPONSE] [MCPE-75813] [Language] Successful
00:13:50.356 | main | INFO | Arisa | 104 | [RESPONSE] [MCPE-75814] [Language] Successful
```
Runs of all modules happen with a delay of 10 seconds. So the first 3 log entries must have happened in the same run, the following must be part of the next run.
It is also noteworthy that the run before that failed completely due to a refused connection, so there were some hiccups on jira at that time
MCPE-75814 was created at 00:12:18.863 UTC.
The only explanation that makes sense here is that the run started ever so slightly *before* `00:12:18.863`. In order to prevent Arisa from missing anything that happened during one run, the time of lastRun is always the timestamp of *before the last successful run started*.

The way the language module works is that it asserts that the issue was created *after* the last run. As explained before, it is, however, possible by design that two runs slightly overlap, when an issue was created ever so slightly after a run started.

I believe this is what happened here.

Usually, modules prevent this by the action they performed not being valid anymore after the module ran (e.g. if TransferVersions transferred versions, all parents have all versions, and the module will return an OperationNotNeededResponse because of that).
In the case of the language module, because it currently doesn't try to resolve and is in the testing phase, this is however not the case.

I am inclined to close this as Won't Fix, since in all other modules this cannot happen, and once this module is implemented fully, it also cannot happen anymore.

**Comment by urielsalis** [comment] 2020-05-06 08:51
Closing as Wont Fix as it will be solved once we enable the language module fully, which by the way, do we want to do now?

**Closed by urielsalis** 2020-05-06 08:51 UTC
Labels: bug
