### ISSUE TITLE
Language module mis-fire

### ISSUE THREAD

**Issue by IonicEcko** [mojira/arisa-kt#142] opened 2020-04-22 09:04 UTC
**Describe the bug**
The bug has very little information but none of it is non-English.

**Example**
https://bugs.mojang.com/browse/MCPE-71549

**Comment by SPGoding** [comment] 2020-04-22 23:19
Maybe Arisa shouldn't check tickets with too little words?

**Comment by Marcono1234** [comment] 2020-04-22 23:56
Another example: https://bugs.mojang.com/browse/MC-180009

**Comment by IonicEcko** [comment] 2020-04-24 04:37
Another example, this one longer than the last https://bugs.mojang.com/browse/MCPE-72386

**Comment by NeunEinser** [comment] 2020-04-24 08:11
Response:
```json
{
    "time": 1,
    "detectedLangs": [
        {
            "lang": "nl",
            "confidence": 0.936
        },
        {
            "lang": "pl",
            "confidence": 0.064
        }
    ],
    "timestamp": "2020-04-24T08:10:29.405"
}
```
It's 93.6% confident that this is Dutch, for whatever reason.

**Comment by IonicEcko** [comment] 2020-04-27 11:29
https://bugs.mojang.com/browse/MCPE-73476 another example

**Comment by MikeUnverferth** [comment] 2020-04-28 14:41
Does the language detection specifically ignore Minecraft-specific words, such as mob/block names? These at least are not likely to be in any language database and might throw off the detection.

**Comment by urielsalis** [comment] 2020-04-28 14:42
Supposedly it uses wikipedia as tokens and ignores those, im guessing Minecraft blocks are in wikipedia?

**Comment by MikeUnverferth** [comment] 2020-04-28 15:02
Often posters will repeat the summary in the description. Might help to check for this and exclude the summary if it is contained in the description (https://bugs.mojang.com/browse/MCPE-72386).

**Comment by IonicEcko** [comment] 2020-04-29 05:15
https://bugs.mojang.com/browse/MCPE-73975 This one doesn't seem to follow the 80% rule.

**Comment by Marcono1234** [comment] 2020-04-29 13:56
Maybe short words with latin chars like "I", "am", "to" and "do" are not unambiguous enough for the currently used service? The Polish chars are pretty unambiguous though I guess.
Therefore maybe it is rather confident that the text is Polish.

**Comment by IonicEcko** [comment] 2020-05-01 02:18
https://bugs.mojang.com/browse/MCPE-74498 another one

**Comment by urielsalis** [comment] 2020-05-06 18:38
Closing while preparing for release, all examples are instances of https://github.com/mojira/arisa-kt/issues/122

**Comment by Marcono1234** [comment] 2020-05-06 19:56
@urielsalis, no it appears not all of them are caused by that. @IonicEcko and @MikeUnverferth have provided examples where this occurred despite the complete report being in English:
- https://bugs.mojang.com/browse/MCPE-73476
- https://bugs.mojang.com/browse/MCPE-72386
- https://bugs.mojang.com/browse/MCPE-74498

Do you know which language Arisa detected? The comment indicates it was none of the handled ones.
Maybe the `lengthThreshold` has to be increased?

**Comment by IonicEcko** [comment] 2020-05-07 01:18
https://bugs.mojang.com/browse/MCPE-75920 This one is completely English but has been flagged.

**Comment by IonicEcko** [comment] 2020-05-07 01:19
https://bugs.mojang.com/browse/MCPE-75920 This one is completely English but has been flagged.

**Comment by SPGoding** [comment] 2020-05-19 05:20
Another two examples from #225:
- https://bugs.mojang.com/browse/MC-182790
- https://bugs.mojang.com/browse/MC-182947

**Closed** 2020-05-19 08:07 UTC
Labels: bug
