### ISSUE TITLE
Resolve reports with future version as "Awaiting Response" instead of replacing version

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#228] opened 2020-05-12 22:26 UTC
## The Problem
The FutureVersionModule currently removes future versions from the list of affected versions and instead adds (what it assumes to be) the latest released version. As discussed internally, this is not always ideal because the version which it adds as a replacement does not necessarily match the version in which the reporter is experiencing the issue in. See also #115.
This can then also cause issues when such a report is resolved as duplicate and the TransferVersionsModule then copies the incorrect versions. See also #229.

Side note: The module currently erroneously assumes that versions in the version list returned by Jira are sorted by release date, however at least for Bedrock edition this is not true. There "1.14.60 Hotfix" comes after "1.16.0.60 Beta" despite it being older. If this feature request is not implemented, the module should at least correctly sort by release date.

## Possible Solution
It was therefore suggested to resolve a report with future version as "Awaiting Response", keep the future version and let the reporter correct it (Arisa would then have to detect this) or let them clarify which version they are experiencing the problem in.
However, if the user added a valid version in addition to a future version, Arisa should only remove the future version and add a comment, but neither resolve the issue nor add an affected version itself.

**Comment by MikeUnverferth** [comment] 2020-05-13 00:38
Another option discussed was for Arisa to change the Affected Version to EMPTY. That was reportedly allowed for an issue updated even though it is not allowed for the initial report.

**Comment by NeunEinser** [comment] 2020-05-15 11:10
Yeah, I think it would make the most sense to always remove the future version, even if it leaves the field empty, and then in case the field is empty, resolve as AR and ask the user to add the correct version again.

**Comment by urielsalis** [comment] 2020-05-17 00:09
Can anyone write a message for what to show in the version is empty?

**Comment by MikeUnverferth** [comment] 2020-05-17 00:44
Please edit the **Affects Version/s** and select the specific **Released Version** you were using when you encountered the reported issue.

**Comment by SPGoding** [comment] 2020-05-17 06:17
Sometimes the reporter selects `Future Version` simply because they can't find the version they were using, which means:
- They are in an wrong project; AND/OR
- They are playing an outdated version.

I think it might be good to mention these two things in the comment.

**Comment by urielsalis** [comment] 2020-05-17 23:26
Caused by: net.rcarz.jiraclient.RestException: 400 : {"errorMessages":[],"errors":{"versions":"Affects Version/s is required."}}

Affects version is required, so it cannot be left empty

**Comment by urielsalis** [comment] 2020-05-19 21:41
We are implementing this by closing as awaiting response after adding the new version

**Closed** 2020-05-19 22:50 UTC
Labels: enhancement
