### ISSUE TITLE
Close tickets referring to MCL-6550 automatically

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#54] opened 2020-04-07 13:13 UTC
It would be great if the bot would automatically close tickets that refer to [MCL-6550](https://bugs.mojang.com/browse/MCL-6550). That could be done by checking whether the ticket's summary, environment or description contain either `not responding` or `-805306369`.

I tried implementing it myself but got too overwhelmed with Arisa's infrastructure; there's `ModuleCrash` but that only checks the ticket's attachments. Additionally, currently it doesn't seem to be possible to run the bot in demo mode (i.e., without actually commenting or trying to resolve).

Moved from https://github.com/mojira/arisa-js/issues/25

**Comment by NeunEinser** [comment] 2020-04-07 13:19
`not responding` can have many contexts, so I'd be a little afraid of false positives here.

**Comment by violine1101** [comment] 2020-04-07 19:40
Yes, I think it's pretty difficult to come up with a check that doesn't result in too many false positives. I guess a good compromise would be to instead
* if the ticket contains `-805306369`: resolve it as a duplicate of MCL-6550 immediately
* if the ticket contains `not responding` (or maybe a few other terms), resolve the ticket as _Awaiting Response_ and leave a comment pointing the user to MCL-6550 for troubleshooting.
Both of these should probably only be executed upon ticket creation.

I think this is probably the best way to have the bot automatically resolve tickets like this without closing too many false positives for good.

**Comment by urielsalis** [comment] 2020-04-08 12:07
I would separate the two of them. Leave this issue for the second one and just add that match to the existing module to solve the first

**Comment by violine1101** [comment] 2020-04-08 19:32
Which existing module do you mean?

**Comment by urielsalis** [comment] 2020-04-08 19:35
The duplicates module

**Comment by NeunEinser** [comment] 2020-04-08 21:29
There is no duplicates module?
Only the crash module, but that currently only works on crash reports, nothing else, and I don't think it would be a good idea to add even more logic to it, it's quite heavy already

**Closed** 2020-05-19 23:05 UTC
Labels: arisa-js, enhancement, good first issue

**Comment by NeunEinser** [comment] 2020-05-20 13:16
Why was this closed?

**Comment by urielsalis** [comment] 2020-05-20 13:18
Not all cases are MCL-6550, and detecting automatically is impossible as
you need more info
