### ISSUE TITLE
Don't reopen old "Awaiting Response" reports if person other than reporter updates it

### ISSUE THREAD

**Issue by Marcono1234** [mojira/arisa-kt#170] opened 2020-04-29 21:23 UTC
## The Problem
One issue #38 tries to solve is that reports which have been resolved as "Awaiting Response" and haven't been updated for a while get reopened by other users which add unrelated comments or attachments. And chances are high that this action is missed and the report therefore incorrectly remains open.

This issue here proposes a possible solution to this problem while not going as far as #38 and requesting resolution changes of the report.

## Suggestion
Only reopen "Awaiting Response" reports if the following applies:
- The report was resolved less than _X_ months ago (can be queried through `resolutiondate` field in API response?, assuming it updates when re-resolving)
- **OR:** The person who performed the update (adding comment or attachment or updating report)  is the reporter

If this does not apply, Arisa should not reopen the report, but instead comment something similar to:
> This report has been resolved a rather long time ago and will not be reopened automatically. If a moderator sees your comment, they will reopen and update the report. However, if you think your update to this report has been overlooked or you want to make sure that this report is reopened, you can contact the Mojira staff on /r/Mojira or the Discord server.

Note: Updates by staff should already be filtered out before and not trigger reopening or the addition of the comment, see also #117.

**Comment by NeunEinser** [comment] 2020-04-29 22:30
I think reports that have confirmation status or have been triaged should always be reopened.

**Comment by Marcono1234** [comment] 2020-04-29 23:06
Though that would then reduce the effectiveness of trying to prevent unrelated comments reopening old reports.

**Comment by NeunEinser** [comment] 2020-04-29 23:51
It would increase the effectiveness of what the module is supposed to do though -- reopen AR tickets if required information is added.

If the ticket is valid and has been confirmed or triaged, there is little reason to close as AR anyways.
The only reasons I see is that repo steps don't work anymore (e.g. seed dependant, but seed does not generate something at all anymore), or we want to know if it still occurs in the latest version.

The problem is that there are "soft" ARs and "hard" ARs. Hard AR is there is actually information missing to be able to understand or reproduce the issue, soft is we understand the issue, we know it's valid, but there is something missing for a newer version of the game.

**Comment by urielsalis** [comment] 2020-04-30 13:19
It was that way before. We changed it to "Any user commenting reopens" under Mojang request https://<url of communication tool>/archives/G0NM0QG14/p1581670165127400

**Comment by urielsalis** [comment] 2020-05-19 22:34
Closing due to above ☝️

**Comment by Marcono1234** [comment] 2020-05-19 23:25
@urielsalis, note that this issue is explicitly only about "old" reports and not reports in general. So I am not sure if the discussion you linked above really applies.

**Comment by urielsalis** [comment] 2020-05-19 23:33
How do we define old?

**Comment by Marcono1234** [comment] 2020-05-20 00:20
Should probably be configurable, but maybe >= 12 months.

**Comment by SPGoding** [comment] 2020-05-21 23:23
The `resolutionDate` _does_ update after re-resolving. e.g. [MC-184810](https://bugs.mojang.com/browse/MC-184810)'s resolutiondate is `2020-05-20T22:43:54.220-0500`

**Closed** 2020-05-26 13:50 UTC
Labels: enhancement
