### ISSUE TITLE
MEQS module removes comments from ticekts triaged before the comment

### ISSUE THREAD

**Issue by urielsalis** [mojira/arisa-kt#40] opened 2020-04-06 14:17 UTC

**Comment by NeunEinser** [comment] 2020-04-06 14:40
If a ticket was triaged, it is a confirmed valid bug by mojang.
Why would you want to add wai or wont fix tags to triaged issues? I'd say this is working as intended ^^

**Closed** 2020-04-06 14:48 UTC
Labels: bug
