### ISSUE TITLE
Resolve tickets as duplicates if a user creates a bunch of tickets with similar/identical names within a period of time

### ISSUE THREAD

**Issue by chandler05** [mojira/arisa-kt#364] opened 2020-07-13 20:13 UTC
## The Problem
I've seen this happen where a user creates TONS of duplicate issues of the excact same ticket and to an extreme.
## Possible Solution
I feel like Arisa should be able to detect if a user is creating more than 5 issues with the same or similar name, all within a short period of time and resolve/delete the duplicates. I think it would not cause as much of a stir when a user does this, and make it a bit easier on the mods

**Comment by NeunEinser** [comment] 2020-07-13 20:17
Duplicate of #187

**Closed by NeunEinser** 2020-07-13 20:17 UTC
Labels: enhancement
